# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20170211_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.IntegerField(default=''),
        ),
    ]
