# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_auto_20170211_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='', max_length=30),
        ),
    ]
